version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: unishare_postgres
    environment:
      POSTGRES_DB: unishareDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: unishare@123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - unishare_network
    restart: unless-stopped

volumes:
  postgres_data:
    name: unishare_postgres_data

networks:
  unishare_network:
    driver: bridge
